### PR TITLE
Support GHC 8.6.2

### PR DESCRIPTION
**Pull request by jkachmar**
This adds support and CI coverage for GHC 8.6.2.

If this looks good, and CI passes smoothly, would you be amenable to this package being added to the Stackage nightly snapshots?

### CODE REVIEW

**Comment by patrickt** [comment]
This looks good to me.

@jkachmar, I’ve opened an issue for Stackage. @robrix is on vacation right now, but I think he’ll be amenable to it - we want people to use this package, after all!

**Comment by patrickt** [comment]
Not sure why this is wedged in the builders.

**Comment by robrix** [comment]
@patrickt: I selected the wrong job in the branch protection settings. Fixed that.

**Comment by robrix** [comment]
Thanks so much @jkachmar!

> If this looks good, and CI passes smoothly, would you be amenable to this package being added to the Stackage nightly snapshots?

I’ve no objection so long as they’re cool with having a 0.x package in there. (In particular, we aren’t promising API stability quite yet.)

**Comment by jkachmar** [comment]
Thanks for getting this merged in!

I don't think there should be any objection to API stability, and once the updated version is published to Hackage I can run the Stackage curator again to make sure that everything works together.

How would you like the attribution/maintainership to be set up in Stackage?

e.g. @patrickt is the Stackage maintainer for `postgresql-transactional` and so shows up in the `build-constraints` file like this: https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml#L2798-L2799

**Comment by robrix** [comment]
@jkachmar: Could you make me the maintainer, with `robrix@github.com` for the email address please? 🙏

**Comment by robrix** [comment]
(I’ve just published 0.1.2.0 to hackage today: http://hackage.haskell.org/package/fused-effects-0.1.2.0)

**Pull request merged**
